import type { WorkoutTemplate } from '../types'

// ============================================
// SYSTEM WORKOUT TEMPLATES
// ============================================

export const SYSTEM_WORKOUT_TEMPLATES: Omit<WorkoutTemplate, 'id' | 'created_at' | 'updated_at'>[] = [
  // ============================================
  // STRENGTH TEMPLATES
  // ============================================
  {
    name: 'Chest Day',
    description: 'Focus on chest muscles with compound and isolation movements',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'chest-1',
        template_id: '',
        body_part: 'chest',
        exercise_name: 'Bench Press',
        equipment: 'Barbell',
        sets: 4,
        reps: 8,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'chest-2',
        template_id: '',
        body_part: 'chest',
        exercise_name: 'Incline Dumbbell Press',
        equipment: 'Dumbbell',
        sets: 3,
        reps: 10,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'chest-3',
        template_id: '',
        body_part: 'chest',
        exercise_name: 'Cable Flyes',
        equipment: 'Cable',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'chest-4',
        template_id: '',
        body_part: 'chest',
        exercise_name: 'Push-ups',
        equipment: 'Bodyweight',
        sets: 3,
        reps: 15,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: 'Back Day',
    description: 'Comprehensive back training for width and thickness',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'back-1',
        template_id: '',
        body_part: 'back',
        exercise_name: 'Deadlift',
        equipment: 'Barbell',
        sets: 4,
        reps: 6,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'back-2',
        template_id: '',
        body_part: 'back',
        exercise_name: 'Pull-ups',
        equipment: 'Bodyweight',
        sets: 4,
        reps: 8,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'back-3',
        template_id: '',
        body_part: 'back',
        exercise_name: 'Bent Over Row',
        equipment: 'Barbell',
        sets: 3,
        reps: 10,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'back-4',
        template_id: '',
        body_part: 'back',
        exercise_name: 'Lat Pulldown',
        equipment: 'Cable',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: 'Leg Day',
    description: 'Complete lower body training session',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'legs-1',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Squat',
        equipment: 'Barbell',
        sets: 4,
        reps: 8,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'legs-2',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Leg Press',
        equipment: 'Machine',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'legs-3',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Romanian Deadlift',
        equipment: 'Barbell',
        sets: 3,
        reps: 10,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'legs-4',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Calf Raises',
        equipment: 'Machine',
        sets: 4,
        reps: 15,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: 'Shoulder Day',
    description: 'Shoulder focused workout for delts and traps',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'shoulders-1',
        template_id: '',
        body_part: 'shoulders',
        exercise_name: 'Overhead Press',
        equipment: 'Barbell',
        sets: 4,
        reps: 8,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'shoulders-2',
        template_id: '',
        body_part: 'shoulders',
        exercise_name: 'Lateral Raises',
        equipment: 'Dumbbell',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'shoulders-3',
        template_id: '',
        body_part: 'shoulders',
        exercise_name: 'Front Raises',
        equipment: 'Dumbbell',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'shoulders-4',
        template_id: '',
        body_part: 'shoulders',
        exercise_name: 'Face Pulls',
        equipment: 'Cable',
        sets: 3,
        reps: 15,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: 'Arm Day',
    description: 'Biceps and triceps focused training',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'arms-1',
        template_id: '',
        body_part: 'arms',
        exercise_name: 'Barbell Curl',
        equipment: 'Barbell',
        sets: 4,
        reps: 10,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'arms-2',
        template_id: '',
        body_part: 'arms',
        exercise_name: 'Tricep Pushdown',
        equipment: 'Cable',
        sets: 4,
        reps: 12,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'arms-3',
        template_id: '',
        body_part: 'arms',
        exercise_name: 'Hammer Curl',
        equipment: 'Dumbbell',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'arms-4',
        template_id: '',
        body_part: 'arms',
        exercise_name: 'Overhead Tricep Extension',
        equipment: 'Dumbbell',
        sets: 3,
        reps: 12,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: 'Core Day',
    description: 'Abdominal and core strength workout',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: 'core-1',
        template_id: '',
        body_part: 'core',
        exercise_name: 'Plank',
        equipment: 'Bodyweight',
        sets: 3,
        reps: 1,
        weight: undefined,
        order_index: 0,
      },
      {
        id: 'core-2',
        template_id: '',
        body_part: 'core',
        exercise_name: 'Crunches',
        equipment: 'Bodyweight',
        sets: 3,
        reps: 20,
        weight: undefined,
        order_index: 1,
      },
      {
        id: 'core-3',
        template_id: '',
        body_part: 'core',
        exercise_name: 'Leg Raises',
        equipment: 'Bodyweight',
        sets: 3,
        reps: 15,
        weight: undefined,
        order_index: 2,
      },
      {
        id: 'core-4',
        template_id: '',
        body_part: 'core',
        exercise_name: 'Russian Twist',
        equipment: 'Bodyweight',
        sets: 3,
        reps: 20,
        weight: undefined,
        order_index: 3,
      },
    ],
  },
  {
    name: '5x5 Strong Lifts',
    description: 'Classic 5x5 strength program with compound movements',
    training_type: 'strength',
    is_system: true,
    template_exercises: [
      {
        id: '5x5-1',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Squat',
        equipment: 'Barbell',
        sets: 5,
        reps: 5,
        weight: undefined,
        order_index: 0,
      },
      {
        id: '5x5-2',
        template_id: '',
        body_part: 'chest',
        exercise_name: 'Bench Press',
        equipment: 'Barbell',
        sets: 5,
        reps: 5,
        weight: undefined,
        order_index: 1,
      },
      {
        id: '5x5-3',
        template_id: '',
        body_part: 'back',
        exercise_name: 'Bent Over Row',
        equipment: 'Barbell',
        sets: 5,
        reps: 5,
        weight: undefined,
        order_index: 2,
      },
      {
        id: '5x5-4',
        template_id: '',
        body_part: 'shoulders',
        exercise_name: 'Overhead Press',
        equipment: 'Barbell',
        sets: 5,
        reps: 5,
        weight: undefined,
        order_index: 3,
      },
      {
        id: '5x5-5',
        template_id: '',
        body_part: 'legs',
        exercise_name: 'Deadlift',
        equipment: 'Barbell',
        sets: 1,
        reps: 5,
        weight: undefined,
        order_index: 4,
      },
    ],
  },

  // ============================================
  // CARDIO TEMPLATES
  // ============================================
  {
    name: 'HIIT Session',
    description: 'High intensity interval training',
    training_type: 'cardio',
    is_system: true,
    template_exercises: [
      {
        id: 'hiit-1',
        template_id: '',
        exercise_name: 'HIIT',
        exercise_type: 'HIIT',
        duration_minutes: 20,
        intensity_level: 'High',
        order_index: 0,
      },
    ],
  },
  {
    name: 'Steady Cardio',
    description: 'Moderate intensity steady state cardio',
    training_type: 'cardio',
    is_system: true,
    template_exercises: [
      {
        id: 'cardio-1',
        template_id: '',
        exercise_name: 'Running',
        exercise_type: 'Running',
        duration_minutes: 30,
        intensity_level: 'Moderate',
        order_index: 0,
      },
    ],
  },
]

// Helper function to get templates by training type
export function getTemplatesByType(trainingType: 'strength' | 'cardio'): typeof SYSTEM_WORKOUT_TEMPLATES {
  return SYSTEM_WORKOUT_TEMPLATES.filter(t => t.training_type === trainingType)
}

// Helper function to get template by name
export function getTemplateByName(name: string): typeof SYSTEM_WORKOUT_TEMPLATES[0] | undefined {
  return SYSTEM_WORKOUT_TEMPLATES.find(t => t.name === name)
}
